//! GPU-parallel constraint solver using graph coloring.
//!
//! Constraint-based physics solver running entirely on the GPU, using graph
//! coloring to solve constraints in parallel without data races. Uses the
//! `Soft-TGS` algorithm (as in Rapier).

use crate::dynamics::joint::{GpuJointSolver, JointSolverArgs};
#[cfg(feature = "dim3")]
use crate::dynamics::multibody::{GpuMultibodySet, GpuMultibodySolver, MultibodySolverArgs};
use crate::math::Pose;
use crate::queries::GpuIndexedContact;
use crate::shaders::dynamics::{
    GpuApplySolverVelsInc, GpuInitSolverBodies, GpuInitSolverVelsInc, GpuIntegrateLinearized,
    GpuSolverCleanup, GpuSolverCountConstraints, GpuSolverFinalize,
    GpuSolverInitConstraints, GpuSolverSortConstraints,
    GpuSolverUpdateConstraints, GpuStepGaussSeidel, GpuStepGaussSeidelFused, GpuWarmstart,
    GpuWarmstartFused, GpuWarmstartWithoutColors,
    LocalMassProperties, RbdSimParams, TwoBodyConstraint, TwoBodyConstraintBuilder, Velocity,
    WorldMassProperties,
};
use crate::utils::{GpuPrefixSum, PrefixSumWorkspace};
use khal::Shader;
use khal::backend::{Encoder, GpuBackend, GpuBackendError, GpuEncoder, GpuPass, GpuTimestamps};
use vortx::tensor::Tensor;

/// GPU shader bundle for the constraint solver.
#[derive(Shader)]
pub struct GpuSolver {
    sort_constraints: GpuSolverSortConstraints,
    /// Initializes constraints from contact manifolds.
    init_constraints: GpuSolverInitConstraints,
    /// Companion counting pass to `init_constraints` (split out to keep each
    /// pass within the 8-storage-buffer WebGPU limit).
    count_constraints: GpuSolverCountConstraints,
    /// Updates nonlinear constraint terms during substeps.
    update_constraints: GpuSolverUpdateConstraints,
    /// Clears solver velocities and constraint counts.
    cleanup: GpuSolverCleanup,
    /// Applies warmstart impulses from previous frame.
    #[allow(dead_code)]
    warmstart: GpuWarmstart,
    /// Applies warmstart impulses from previous frame, without relying on graph coloring.
    warmstart_without_colors: GpuWarmstartWithoutColors,
    /// Gauss-Seidel iteration step (sequential per color).
    step_gauss_seidel: GpuStepGaussSeidel,
    /// Fused variant of the colored warmstart sweep: one workgroup per batch
    /// loops every color internally (barrier between colors). Used when
    /// per-batch constraint counts are small — see `SolverArgs::fused_color_sweeps`.
    warmstart_fused: GpuWarmstartFused,
    /// Fused variant of the colored Gauss-Seidel sweep (same rationale).
    step_gauss_seidel_fused: GpuStepGaussSeidelFused,
    /// Initializes solver velocity increments.
    init_solver_vels_inc: GpuInitSolverVelsInc,
    /// Seeds the COM-centered solver poses from the body world poses
    /// (rapier's `SolverBodies::copy_from`). Run once per step.
    init_solver_bodies: GpuInitSolverBodies,
    /// Applies accumulated solver velocity increments.
    apply_solver_vels_inc: GpuApplySolverVelsInc,
    /// Integrates positions from velocities.
    integrate_linearized: GpuIntegrateLinearized,
    /// Writes solver velocities and converts the COM-centered solver poses
    /// back to body-origin poses.
    finalize: GpuSolverFinalize,
}

/// Arguments for constraint solver dispatch, used by [`GpuSolver::prepare`] and
/// [`GpuSolver::solve_tgs`].

/// Capacity-based dispatch grid for the contact-count-driven solver kernels
/// (used when fixed-grid dispatch replaces the indirect buffer; see
/// `crate::dispatch_grid`).
fn contacts_grid(args: &SolverArgs) -> [u32; 3] {
    let nb = args.num_batches.max(1);
    [
        (args.contacts.len() as u32 / nb).max(1).div_ceil(64),
        args.num_batches.max(1),
        1,
    ]
}

pub struct SolverArgs<'a> {
    /// Total number of colors from graph coloring.
    pub num_colors: u32,
    /// Number of simulation batches.
    pub num_batches: u32,
    /// Number of colliders.
    pub num_colliders: u32,
    /// Contact manifolds generated by narrow-phase.
    pub contacts: &'a Tensor<GpuIndexedContact>,
    /// Number of contacts (per batch).
    pub contacts_len: &'a Tensor<u32>,
    /// Indirect dispatch arguments based on contact count.
    pub contacts_len_indirect: &'a Tensor<[u32; 3]>,
    /// Solver constraints (output from constraint initialization).
    pub constraints: &'a mut Tensor<TwoBodyConstraint>,
    /// Builder data for initializing constraints.
    pub constraint_builders: &'a mut Tensor<TwoBodyConstraintBuilder>,
    /// Global simulation parameters.
    pub sim_params: &'a Tensor<RbdSimParams>,
    /// Rigid body world-origin poses. Mirrors rapier's `RigidBody::position`.
    /// Read at the start of each step to seed [`Self::solver_body_poses`] and
    /// written back at the end of the substep loop by `finalize`.
    pub body_poses: &'a mut Tensor<Pose>,
    /// Rigid-body poses centered at the rigid-body center-of-mass — rapier's
    /// `SolverPose`. This is the only pose buffer the solver substep loop
    /// touches. Seeded from `body_poses` at step start and written back to
    /// `body_poses` at step end.
    pub solver_body_poses: &'a mut Tensor<Pose>,
    /// Per-collider local pose relative to the rigid-body it is attached to.
    pub collider_local_poses: &'a Tensor<Pose>,
    /// Per-collider world poses (= `body_poses[i] * collider_local_poses[i]`),
    /// kept up-to-date once per step before broad/narrow-phase.
    pub collider_world_poses: &'a Tensor<Pose>,
    /// Rigid body velocities.
    pub vels: &'a mut Tensor<Velocity>,
    /// Solver working velocities.
    pub solver_vels: &'a mut Tensor<Velocity>,
    /// Accumulated velocity increments during substeps.
    pub solver_vels_inc: &'a mut Tensor<Velocity>,
    /// World-space mass properties.
    pub mprops: &'a Tensor<WorldMassProperties>,
    /// Local-space mass properties.
    pub local_mprops: &'a Tensor<LocalMassProperties>,
    /// Number of constraints per body.
    ///
    /// All constraints of all the bodies part of the same multibody are counted in a single
    /// entry at its root’s body index.
    pub body_constraint_counts: &'a mut Tensor<u32>,
    /// Constraint IDs associated with each body.
    ///
    /// All constraints of all the bodies part of the same multibody are in the same list associated
    /// to the multibody’s root.
    pub body_constraint_ids: &'a mut Tensor<u32>,
    /// Per-batch per-color exclusive prefix sums over the color-bucketed
    /// constraint ids (stride `BatchIndices::solver_color_buckets_stride`).
    pub color_bucket_starts: &'a Tensor<u32>,
    /// Constraint ids bucket-sorted by color (contacts layout).
    pub color_sorted_ids: &'a Tensor<u32>,
    /// Per-color-index uniform tensors: `color_uniforms[c]` holds the constant
    /// `c`. Bound (instead of a GPU-incremented cursor) by each color-sweep
    /// dispatch, which removes the 1-thread `reset_color`/`inc_color`
    /// dispatches (and their barriers) from every color loop.
    pub color_uniforms: &'a [Tensor<u32>],
    /// Prefix sum shader for building constraint ranges.
    pub prefix_sum: &'a GpuPrefixSum,
    /// Number of solver iterations (max across all environments).
    pub num_solver_iterations: u32,
    /// Per-body graph-coloring group id (multibody-aware).
    pub body_group: &'a Tensor<u32>,
    /// When `true` (no multibody in the scene), warmstart uses the single
    /// gather-per-body dispatch instead of one scatter dispatch per color.
    /// The gather variant looks bodies up by their own id, which is only
    /// correct when `body_group` is the identity (multibody constraints are
    /// counted on their root's slot with link-id constraint sides).
    pub colorless_warmstart: bool,
    /// When `true`, each colored sweep (warmstart / Gauss-Seidel) runs as ONE
    /// dispatch with one workgroup per batch looping the colors internally,
    /// instead of `num_colors` dispatches. A single 64-lane workgroup
    /// serializes large buckets, so the caller enables this only when the
    /// per-batch constraint count is small (tiny environments / single robot),
    /// where the per-color dispatches and their empty buckets dominate.
    /// Correct for any size — this is a performance gate only.
    pub fused_color_sweeps: bool,
    /// `true` when every rigid-body contact constraint is provably a no-op
    /// (no body has a nonzero rb-side inverse mass — robot-only scenes; see
    /// `RbdState::rb_contacts_inert`). Skips the contact-constraint build,
    /// coloring inputs, warmstart, colored sweeps and integration; the joint
    /// solver and the multibody solver are unaffected.
    pub rb_contacts_inert: bool,
    /// Shared per-batch capacity / section-offset uniform — see
    /// [`crate::shaders::utils::BatchIndices`]. Consumed by the (refactored)
    /// multibody kernels via `MultibodySolverArgs::batch_indices`; the RBD
    /// constraint-solver kernels will migrate to it next.
    pub batch_indices: &'a Tensor<crate::shaders::utils::BatchIndices>,
    /// GPU-written workgroup grid for the per-multibody contact-constraint
    /// dispatches (zero workgroups on contact-free steps) — forwarded to
    /// [`MultibodySolverArgs::mb_sweep_indirect`].
    pub mb_sweep_indirect: &'a Tensor<[u32; 3]>,
}

impl GpuSolver {
    /// Prepares constraints for solving (init, prefix sum, sort).
    pub fn prepare<'a>(
        &self,
        backend: &GpuBackend,
        pass: &mut GpuPass,
        args: SolverArgs<'a>,
        prefix_sum_workspace: &'a mut PrefixSumWorkspace,
    ) -> Result<(), GpuBackendError> {
        // Cleanup zeroes body_constraint_counts, solver_vels, vels, mprops.
        self.cleanup.call(
            pass,
            [args.num_colliders, args.num_batches, 1],
            args.body_constraint_counts,
            args.solver_vels,
            args.vels,
            args.mprops,
            args.batch_indices,
        )?;

        // Seed `solver_body_poses` from `body_poses`: rapier's
        // `SolverBodies::copy_from`. After this, only the COM-centered solver
        // poses are touched until the final `finalize` writeback.
        // Independent of `cleanup` (different buffers), but `init_constraints`
        // below reads `solver_body_poses` so we barrier before it.
        self.init_solver_bodies.call(
            pass,
            [args.num_colliders, args.num_batches, 1],
            args.body_poses,
            args.local_mprops,
            args.solver_body_poses,
            args.batch_indices,
        )?;

        // Robot-only scenes: every rigid-body contact constraint is a no-op
        // (see `SolverArgs::rb_contacts_inert`) — skip the build/count/sort
        // chain entirely. `cleanup` and `init_solver_bodies` above still run
        // (the multibody phases rely on zeroed solver velocities and seeded
        // solver poses).
        if args.rb_contacts_inert {
            return Ok(());
        }

        self.init_constraints.call(
            pass,
            crate::dispatch_grid(args.contacts_len_indirect, contacts_grid(&args)),
            args.contacts,
            args.constraints,
            args.constraint_builders,
            args.collider_world_poses,
            args.solver_body_poses,
            args.vels,
            args.mprops,
            args.sim_params,
            args.batch_indices,
        )?;

        // Counting runs as a separate dispatch (same indirect grid) so the
        // build pass above stays within 8 storage buffers.
        self.count_constraints.call(
            pass,
            crate::dispatch_grid(args.contacts_len_indirect, contacts_grid(&args)),
            args.contacts,
            args.body_constraint_counts,
            args.body_group,
            args.mprops,
            args.contacts_len,
            args.batch_indices,
        )?;

        args.prefix_sum.launch(
            backend,
            pass,
            prefix_sum_workspace,
            args.body_constraint_counts,
            args.num_batches,
        )?;

        self.sort_constraints.call(
            pass,
            crate::dispatch_grid(args.contacts_len_indirect, contacts_grid(&args)),
            args.body_constraint_counts,
            args.mprops,
            args.contacts,
            args.contacts_len,
            args.body_constraint_ids,
            args.body_group,
            args.batch_indices,
        )?;

        Ok(())
    }

    /// Solves constraints using the TGS (Total Gauss-Seidel) algorithm.
    ///
    /// When `multibody` is `Some`, multibody substep work is interleaved with
    /// the rigid-body substep work — one `multibody.apply_substep` call inside
    /// each iteration of the substep loop, just like rapier's
    /// `velocity_solver::solve_constraints`.
    pub fn solve_tgs<'a>(
        &self,
        encoder: &mut GpuEncoder,
        mut timestamps: Option<&mut GpuTimestamps>,
        joint_solver: &GpuJointSolver,
        args: SolverArgs<'a>,
        mut joint_args: JointSolverArgs<'a>,
        #[cfg(feature = "dim3")] multibody: Option<(&GpuMultibodySolver, &mut GpuMultibodySet)>,
    ) -> Result<(), GpuBackendError> {
        let num_substeps = args.num_solver_iterations;
        #[cfg(feature = "dim3")]
        let (mb_solver, mut mb_state) = match multibody {
            Some((s, st)) => (Some(s), Some(st)),
            None => (None, None),
        };
        // Robot-only scenes: every rigid-body CONTACT constraint is a no-op
        // (see `SolverArgs::rb_contacts_inert`) — the gravity increments,
        // contact warmstart/sweeps and free-body integration below all read
        // or write only zero-inv-mass bodies, so they are skipped. The joint
        // solver stays (it no-ops on an empty set anyway).
        let skip_rb = args.rb_contacts_inert;
        let joints_empty = joint_args.joints.is_empty();

        /*
         * Init solver vel increments.
         */
        {
            let mut pass = encoder.begin_pass("[RBD] slv/init", timestamps.as_deref_mut());
            if !skip_rb {
                self.init_solver_vels_inc.call(
                    &mut pass,
                    [args.num_colliders, args.num_batches, 1],
                    args.solver_vels_inc,
                    args.mprops,
                    args.sim_params,
                    args.batch_indices,
                )?;
            }

            joint_solver.init(&mut pass, &mut joint_args)?;

            // Bound for the per-substep contact scans: runs after the narrow
            // phase wrote `contacts_len`, before the first substep build.
            #[cfg(feature = "dim3")]
            if let (Some(solver), Some(state)) = (mb_solver, mb_state.as_deref_mut()) {
                let mut mb_args = MultibodySolverArgs {
                    poses: &mut *args.solver_body_poses,
                    collider_world_poses: args.collider_world_poses,
                    mprops: args.mprops,
                    contacts: args.contacts,
                    contacts_len: args.contacts_len,
                    solver_vels: &mut *args.solver_vels,
                    batch_indices: args.batch_indices,
                    color_uniforms: args.color_uniforms,
                    mb_sweep_indirect: args.mb_sweep_indirect,
                };
                solver.stash_contacts_len(&mut pass, state, &mut mb_args)?;
            }
        }

        // Explicit-coriolis mode: the multibody contact constraints only
        // depend on per-step constants (manifolds, collider world poses, the
        // once-per-step body jacobians and mass-matrix LU), so build them ONCE
        // here instead of once per substep. The accumulated impulses still
        // persist in the constraint slots across substeps, exactly as with
        // the per-substep rebuild (which preserved them explicitly).
        #[cfg(feature = "dim3")]
        if let (Some(solver), Some(state)) = (mb_solver, mb_state.as_deref_mut()) {
            if !state.implicit_coriolis() {
                let mut mb_args = MultibodySolverArgs {
                    poses: &mut *args.solver_body_poses,
                    collider_world_poses: args.collider_world_poses,
                    mprops: args.mprops,
                    contacts: args.contacts,
                    contacts_len: args.contacts_len,
                    solver_vels: &mut *args.solver_vels,
                    batch_indices: args.batch_indices,
                    color_uniforms: args.color_uniforms,
                    mb_sweep_indirect: args.mb_sweep_indirect,
                };
                solver.build_contact_constraints(
                    encoder,
                    timestamps.as_deref_mut(),
                    state,
                    &mut mb_args,
                )?;
            }
        }

        // Per substep, the multibody work is split into five phases that are
        // INTERLEAVED with the matching rigid-body phases, mirroring rapier's
        // `velocity_solver::solve_constraints` order:
        //   P1/F1  integrate all velocities
        //   P2/F2  build + warmstart all constraints
        //   P3/F3  one PGS sweep over ALL joints + contacts WITH bias
        //   P4/F4  integrate ALL positions ONCE
        //   P5/F5  one PGS sweep over ALL joints + contacts WITHOUT bias
        // (Previously the entire multibody solve — including its own position
        // integration — ran as a monolithic block BEFORE the rigid-body solve,
        // which de-synchronised mb↔free contact coupling.)
        //
        // Each `mb_phase!($method $(, $extra)*)` invocation runs one multibody
        // phase. It is `#[cfg(feature = "dim3")]`-gated (the multibody solver
        // only exists in 3D) and reconstructs `mb_args` each time — the borrow
        // of `args.solver_vels` / `args.solver_body_poses` must be released
        // before the interleaved rigid-body call that touches the same buffers.
        macro_rules! mb_phase {
            ($label:expr, $method:ident $(, $extra:expr)*) => {{
                #[cfg(feature = "dim3")]
                if let (Some(solver), Some(state)) = (mb_solver, mb_state.as_deref_mut()) {
                    let mut pass = encoder.begin_pass($label, timestamps.as_deref_mut());
                    let mut mb_args = MultibodySolverArgs {
                        poses: &mut *args.solver_body_poses,
                        collider_world_poses: args.collider_world_poses,
                        mprops: args.mprops,
                        contacts: args.contacts,
                        contacts_len: args.contacts_len,
                        solver_vels: &mut *args.solver_vels,
                        batch_indices: args.batch_indices,
                        color_uniforms: args.color_uniforms,
                        mb_sweep_indirect: args.mb_sweep_indirect,
                    };
                    solver.$method(&mut pass, state, &mut mb_args $(, $extra)*)?;
                }
            }};
        }

        for substep_id in 0..num_substeps {
            let is_last_substep = substep_id == num_substeps - 1;
            // Only consumed by the dim3-only multibody phases.
            #[cfg(not(feature = "dim3"))]
            let _ = is_last_substep;

            /*
             * P1/F1 — integrate velocities (apply `a · dt'` / gravity increment).
             */
            mb_phase!("[RBD] slv/mb-integrate-vels", substep_integrate_velocities);
            if !skip_rb {
                let mut pass =
                    encoder.begin_pass("[RBD] slv/rb-apply-inc", timestamps.as_deref_mut());
                self.apply_solver_vels_inc.call(
                    &mut pass,
                    [args.num_colliders, args.num_batches, 1],
                    args.solver_vels,
                    args.solver_vels_inc,
                    args.batch_indices,
                )?;
            }

            /*
             * P2/F2 — build + warmstart constraints.
             */
            {
                #[cfg(feature = "dim3")]
                if let (Some(solver), Some(state)) = (mb_solver, mb_state.as_deref_mut()) {
                    let mut mb_args = MultibodySolverArgs {
                        poses: &mut *args.solver_body_poses,
                        collider_world_poses: args.collider_world_poses,
                        mprops: args.mprops,
                        contacts: args.contacts,
                        contacts_len: args.contacts_len,
                        solver_vels: &mut *args.solver_vels,
                        batch_indices: args.batch_indices,
                        color_uniforms: args.color_uniforms,
                        mb_sweep_indirect: args.mb_sweep_indirect,
                    };
                    solver.substep_build_constraints(
                        encoder,
                        timestamps.as_deref_mut(),
                        state,
                        &mut mb_args,
                        substep_id == 0,
                    )?;
                }
            }
            if !skip_rb || !joints_empty {
                let mut pass =
                    encoder.begin_pass("[RBD] slv/rb-build-warmstart", timestamps.as_deref_mut());
                let pass = &mut pass;
                if !skip_rb {
                    self.update_constraints.call(
                        pass,
                        crate::dispatch_grid(args.contacts_len_indirect, contacts_grid(&args)),
                        args.constraints,
                        args.constraint_builders,
                        args.contacts_len,
                        args.solver_body_poses,
                        args.sim_params,
                        args.batch_indices,
                    )?;
                }
                joint_solver.update(pass, &mut joint_args, args.solver_body_poses)?;
                if skip_rb {
                    // Contact warmstart skipped: no rigid-body contact
                    // constraint can carry an impulse here.
                } else if args.colorless_warmstart {
                    // One gather dispatch over bodies instead of `num_colors`
                    // scatter dispatches (each constraint is visited once per
                    // body side, but the dispatch count drops by ~num_colors).
                    self.warmstart_without_colors.call(
                        pass,
                        [args.num_colliders, args.num_batches, 1],
                        args.body_constraint_counts,
                        args.body_constraint_ids,
                        args.constraints,
                        args.solver_vels,
                        args.batch_indices,
                    )?;
                } else if args.fused_color_sweeps {
                    // One dispatch, one workgroup per batch, colors looped
                    // internally. `color_uniforms[num_colors]` holds the
                    // constant `num_colors`.
                    self.warmstart_fused.call(
                        pass,
                        [64, args.num_batches, 1],
                        args.constraints,
                        args.solver_vels,
                        args.color_bucket_starts,
                        args.color_sorted_ids,
                        &args.color_uniforms[args.num_colors as usize],
                        args.batch_indices,
                    )?;
                } else {
                    // NOTE: contact colors start at 1 (0 = unassigned).
                    for c in 1..=args.num_colors {
                        self.warmstart.call(
                            pass,
                            crate::dispatch_grid(args.contacts_len_indirect, contacts_grid(&args)),
                            args.constraints,
                            args.solver_vels,
                            args.color_bucket_starts,
                            args.color_sorted_ids,
                            &args.color_uniforms[c as usize],
                            args.batch_indices,
                        )?;
                    }
                }
            }

            /*
             * P3/F3 — solve ALL joints + contacts WITH bias.
             */
            mb_phase!("[RBD] slv/mb-solve-bias", substep_solve_with_bias);
            if !skip_rb || !joints_empty {
                let mut pass =
                    encoder.begin_pass("[RBD] slv/rb-solve-bias", timestamps.as_deref_mut());
                let pass = &mut pass;
                joint_solver.solve(pass, &mut joint_args, args.solver_vels, true)?;
                if skip_rb {
                    // Contact sweeps skipped (inert constraints).
                } else if args.fused_color_sweeps {
                    self.step_gauss_seidel_fused.call(
                        pass,
                        [64, args.num_batches, 1],
                        args.constraints,
                        args.solver_vels,
                        args.color_bucket_starts,
                        args.color_sorted_ids,
                        &args.color_uniforms[args.num_colors as usize],
                        args.batch_indices,
                        // use_bias = 1 (`color_uniforms[c]` holds the constant `c`).
                        &args.color_uniforms[1],
                    )?;
                } else {
                    for c in 1..=args.num_colors {
                        self.step_gauss_seidel.call(
                            pass,
                            crate::dispatch_grid(args.contacts_len_indirect, contacts_grid(&args)),
                            args.constraints,
                            args.solver_vels,
                            args.color_bucket_starts,
                            args.color_sorted_ids,
                            &args.color_uniforms[c as usize],
                            args.batch_indices,
                            // use_bias = 1 (`color_uniforms[c]` holds the constant `c`).
                            &args.color_uniforms[1],
                        )?;
                    }
                }
            }

            /*
             * P4/F4 — integrate ALL positions once.
             */
            mb_phase!(
                "[RBD] slv/mb-integrate-pos",
                substep_integrate_positions,
                is_last_substep
            );
            if !skip_rb {
                let mut pass =
                    encoder.begin_pass("[RBD] slv/rb-integrate", timestamps.as_deref_mut());
                self.integrate_linearized.call(
                    &mut pass,
                    [args.num_colliders, args.num_batches, 1],
                    args.solver_body_poses,
                    args.solver_vels,
                    args.sim_params,
                    args.batch_indices,
                )?;
            }

            /*
             * P5/F5 — solve ALL joints + contacts WITHOUT bias (stabilization).
             */
            mb_phase!(
                "[RBD] slv/mb-solve-nobias",
                substep_solve_no_bias,
                is_last_substep
            );
            if !skip_rb || !joints_empty {
                let mut pass =
                    encoder.begin_pass("[RBD] slv/rb-solve-nobias", timestamps.as_deref_mut());
                let pass = &mut pass;
                joint_solver.solve(pass, &mut joint_args, args.solver_vels, false)?;
                if skip_rb {
                    // Contact sweeps skipped (inert constraints).
                } else if args.fused_color_sweeps {
                    self.step_gauss_seidel_fused.call(
                        pass,
                        [64, args.num_batches, 1],
                        args.constraints,
                        args.solver_vels,
                        args.color_bucket_starts,
                        args.color_sorted_ids,
                        &args.color_uniforms[args.num_colors as usize],
                        args.batch_indices,
                        // use_bias = 0 (`color_uniforms[c]` holds the constant `c`).
                        &args.color_uniforms[0],
                    )?;
                } else {
                    for c in 1..=args.num_colors {
                        self.step_gauss_seidel.call(
                            pass,
                            crate::dispatch_grid(args.contacts_len_indirect, contacts_grid(&args)),
                            args.constraints,
                            args.solver_vels,
                            args.color_bucket_starts,
                            args.color_sorted_ids,
                            &args.color_uniforms[c as usize],
                            args.batch_indices,
                            // use_bias = 0 (`color_uniforms[c]` holds the constant `c`).
                            &args.color_uniforms[0],
                        )?;
                    }
                }
            }
        }

        /*
         * Writeback body velocities and convert COM-centered solver poses
         * back to body-origin poses.
         */
        {
            let mut pass = encoder.begin_pass("[RBD] slv/finalize", timestamps.as_deref_mut());
            self.finalize.call(
                &mut pass,
                [args.num_colliders, args.num_batches, 1],
                args.vels,
                args.solver_vels,
                args.body_poses,
                args.solver_body_poses,
                args.local_mprops,
                args.batch_indices,
            )?;
        }

        Ok(())
    }
}
