//! GPU-parallel constraint solver using graph coloring.
//!
//! This module implements a constraint-based physics solver that runs entirely on the GPU.
//! It uses graph coloring to enable parallel constraint solving while avoiding data races.
//!
//! # Solver Variants
//!
//! The module supports one main solver algorithm:
//!
//! - `Soft-TGS` (the same approach as Rapier and other engines like Box2D). This operates by splitting the simulation
//!   timestep into smaller substeps in order to lower errors caused by nonlinearities (e.g. rotations). Each substep
//!   is solved with a single PGS iteration (with bias) followed by position update, followed by another PGS iteration
//!   (without bias).

use crate::dynamics::joint::{GpuJointSolver, JointSolverArgs};
use crate::utils::{GpuPrefixSum, PrefixSumWorkspace};
use crate::math::Pose;
use crate::queries::GpuIndexedContact;
use crate::shaders::dynamics::{
    GpuApplySolverVelsInc, GpuInitSolverVelsInc, GpuIntegrate, GpuRemoveCfmAndBiasKernel,
    GpuSolverCleanup, GpuSolverFinalize, GpuSolverIncColor, GpuSolverInitConstraints,
    GpuSolverResetColor, GpuSolverSortConstraints, GpuSolverUpdateConstraints, GpuStepGaussSeidel,
    GpuWarmstart, GpuWarmstartWithoutColors, LocalMassProperties, SimParams, TwoBodyConstraint,
    TwoBodyConstraintBuilder, Velocity, WorldMassProperties,
};
use khal::Shader;
use khal::backend::{GpuBackend, GpuBackendError, GpuPass};
use vortx::tensor::Tensor;

/// GPU shader bundle for the constraint solver.
///
/// This shader contains all the compute pipelines needed for constraint-based physics solving,
/// including constraint initialization, sorting, solving, and integration.
#[derive(Shader)]
pub struct GpuSolver {
    sort_constraints: GpuSolverSortConstraints,
    reset_color: GpuSolverResetColor,
    inc_color: GpuSolverIncColor,
    /// Initializes constraints from contact manifolds.
    init_constraints: GpuSolverInitConstraints,
    /// Updates nonlinear constraint terms during substeps.
    update_constraints: GpuSolverUpdateConstraints,
    /// Clears solver velocities and constraint counts.
    cleanup: GpuSolverCleanup,
    /// Applies warmstart impulses from previous frame.
    warmstart: GpuWarmstart,
    /// Applies warmstart impulses from previous frame, without relying on graph coloring.
    #[allow(dead_code)]
    warmstart_without_colors: GpuWarmstartWithoutColors,
    /// Gauss-Seidel iteration step (sequential per color).
    step_gauss_seidel: GpuStepGaussSeidel,
    /// Initializes solver velocity increments.
    init_solver_vels_inc: GpuInitSolverVelsInc,
    /// Applies accumulated solver velocity increments.
    apply_solver_vels_inc: GpuApplySolverVelsInc,
    /// Integrates positions from velocities.
    integrate: GpuIntegrate,
    /// Writes solver velocities back to body storage.
    finalize: GpuSolverFinalize,
    /// Removes CFM and bias terms for velocity-only solving.
    remove_cfm_and_bias_kernel: GpuRemoveCfmAndBiasKernel,
}

/// Arguments for constraint solver dispatch.
///
/// This structure bundles all the GPU buffers and parameters needed for running
/// the constraint solver. It's used by both the [`GpuSolver::prepare`] and
/// [`GpuSolver::solve_tgs`] methods.
pub struct SolverArgs<'a> {
    /// Total number of colors from graph coloring.
    pub num_colors: u32,
    /// Number of simulation batches.
    pub num_batches: u32,
    /// Number of colliders.
    pub num_colliders: u32,
    /// Contact manifolds generated by narrow-phase.
    pub contacts: &'a Tensor<GpuIndexedContact>,
    /// Number of contacts (per batch).
    pub contacts_len: &'a Tensor<u32>,
    /// Indirect dispatch arguments based on contact count.
    pub contacts_len_indirect: &'a Tensor<[u32; 3]>,
    /// Solver constraints (output from constraint initialization).
    pub constraints: &'a mut Tensor<TwoBodyConstraint>,
    /// Builder data for initializing constraints.
    pub constraint_builders: &'a mut Tensor<TwoBodyConstraintBuilder>,
    /// Global simulation parameters.
    pub sim_params: &'a Tensor<SimParams>,
    /// Number of colliders per batch (uniform scalar, used as loop bound).
    pub colliders_len: &'a Tensor<u32>,
    /// Rigid body poses.
    pub poses: &'a mut Tensor<Pose>,
    /// Rigid body velocities.
    pub vels: &'a mut Tensor<Velocity>,
    /// Solver working velocities.
    pub solver_vels: &'a mut Tensor<Velocity>,
    /// Solver output velocities (currently unused).
    pub solver_vels_out: &'a Tensor<Velocity>,
    /// Accumulated velocity increments during substeps.
    pub solver_vels_inc: &'a mut Tensor<Velocity>,
    /// World-space mass properties.
    pub mprops: &'a Tensor<WorldMassProperties>,
    /// Local-space mass properties.
    pub local_mprops: &'a Tensor<LocalMassProperties>,
    /// Number of constraints per body.
    pub body_constraint_counts: &'a mut Tensor<u32>,
    /// Constraint IDs associated with each body.
    pub body_constraint_ids: &'a mut Tensor<u32>,
    /// Color assigned to each constraint by graph coloring.
    pub constraints_colors: &'a Tensor<u32>,
    /// Current color being processed.
    pub curr_color: &'a mut Tensor<u32>,
    /// Prefix sum shader for building constraint ranges.
    pub prefix_sum: &'a GpuPrefixSum,
    /// Maximum contacts per batch (stride between batches in contact buffers).
    pub contacts_batch_capacity: &'a Tensor<u32>,
    /// Maximum colliders per batch (stride between batches in body buffers).
    pub colliders_batch_capacity: &'a Tensor<u32>,
    /// Number of solver iterations (max across all environments).
    pub num_solver_iterations: u32,
}

impl GpuSolver {
    /// Prepares constraints for solving.
    ///
    /// This method:
    /// 1. Clears solver velocities and constraint counts
    /// 2. Initializes constraints from contact manifolds
    /// 3. Performs prefix sum to build body-to-constraint mapping
    /// 4. Sorts constraints by body pairs
    ///
    /// # Parameters
    ///
    /// - `pass`: The compute pass to record commands into
    /// - `args`: Solver arguments containing all necessary buffers
    /// - `prefix_sum_workspace`: Workspace for the prefix sum algorithm
    ///
    /// # GPU Performance
    ///
    /// Uses indirect dispatches based on the number of contacts, allowing the GPU
    /// to handle variable workloads efficiently.
    pub fn prepare<'a>(
        &self,
        backend: &GpuBackend,
        pass: &mut GpuPass,
        args: SolverArgs<'a>,
        prefix_sum_workspace: &'a mut PrefixSumWorkspace,
    ) -> Result<(), GpuBackendError> {
        // Cleanup
        self.cleanup.call(
            pass,
            [args.num_colliders, args.num_batches, 1],
            args.body_constraint_counts,
            args.solver_vels,
            args.vels,
            args.mprops,
            args.colliders_len,
            args.colliders_batch_capacity,
        )?;

        // Init constraints
        self.init_constraints.call(
            pass,
            args.contacts_len_indirect,
            args.contacts,
            args.contacts_len,
            args.constraints,
            args.constraint_builders,
            args.body_constraint_counts,
            args.poses,
            args.vels,
            args.mprops,
            args.sim_params,
            args.contacts_batch_capacity,
            args.colliders_batch_capacity,
        )?;

        // Prefix sum (per-batch)
        args.prefix_sum.launch(
            backend,
            pass,
            prefix_sum_workspace,
            args.body_constraint_counts,
            args.num_batches,
        )?;

        self.sort_constraints.call(
            pass,
            args.contacts_len_indirect,
            args.body_constraint_counts,
            args.mprops,
            args.contacts,
            args.contacts_len,
            args.body_constraint_ids,
            args.contacts_batch_capacity,
            args.colliders_batch_capacity,
        )?;

        Ok(())
    }

    /// Solves constraints using the TGS (Total Gauss-Seidel) algorithm.
    ///
    /// TGS is a constraint solver that provides better stability and convergence
    /// than traditional PGS. It uses multiple substeps with intermediate position integration
    /// and separate phases for bias (penetration correction) and velocity solving.
    ///
    /// # Algorithm Steps (per substep)
    ///
    /// 1. Apply accumulated velocity increments.
    /// 2. Update nonlinear constraint terms based on new positions.
    /// 3. Warmstart: apply previous frame's impulses.
    /// 4. Solve with bias: correct penetrations.
    /// 5. Integrate positions.
    /// 6. Solve without bias: solve for velocities only.
    pub fn solve_tgs<'a>(
        &self,
        pass: &mut GpuPass,
        joint_solver: &GpuJointSolver,
        args: SolverArgs<'a>,
        mut joint_args: JointSolverArgs<'a>,
    ) -> Result<(), GpuBackendError> {
        let num_substeps = args.num_solver_iterations;

        /*
         * Init solver vel increments.
         */
        self.init_solver_vels_inc.call(
            pass,
            [args.num_colliders, args.num_batches, 1],
            args.solver_vels_inc,
            args.mprops,
            args.colliders_len,
            args.sim_params,
            args.colliders_batch_capacity,
        )?;

        joint_solver.init(pass, &mut joint_args)?;

        for _ in 0..num_substeps {
            /*
             * Apply solver velocities increments.
             */
            self.apply_solver_vels_inc.call(
                pass,
                [args.num_colliders, args.num_batches, 1],
                args.solver_vels,
                args.solver_vels_inc,
                args.colliders_len,
                args.colliders_batch_capacity,
            )?;

            /*
             * Update nonlinear terms.
             */
            self.update_constraints.call(
                pass,
                args.contacts_len_indirect,
                args.constraints,
                args.constraint_builders,
                args.contacts_len,
                args.poses,
                args.sim_params,
                args.contacts_batch_capacity,
                args.colliders_batch_capacity,
            )?;

            joint_solver.update(pass, &mut joint_args, args.poses)?;

            /*
             * Warmstart.
             */
            self.reset_color.call(pass, 1u32, args.curr_color)?;
            for _ in 0..args.num_colors {
                self.warmstart.call(
                    pass,
                    args.contacts_len_indirect,
                    args.constraints,
                    args.solver_vels,
                    args.constraints_colors,
                    args.contacts_len,
                    args.curr_color,
                    args.contacts_batch_capacity,
                    args.colliders_batch_capacity,
                )?;
                self.inc_color.call(pass, 1u32, args.curr_color)?
            }

            /*
             * Solve with bias.
             */
            joint_solver.solve(pass, &mut joint_args, args.solver_vels, true)?;
            self.reset_color.call(pass, 1u32, args.curr_color)?;
            for _ in 0..args.num_colors {
                self.step_gauss_seidel.call(
                    pass,
                    args.contacts_len_indirect,
                    args.constraints,
                    args.solver_vels,
                    args.constraints_colors,
                    args.contacts_len,
                    args.curr_color,
                    args.contacts_batch_capacity,
                    args.colliders_batch_capacity,
                )?;
                self.inc_color.call(pass, 1u32, args.curr_color)?
            }

            /*
             * Integrate positions only.
             */
            self.integrate.call(
                pass,
                [args.num_colliders, args.num_batches, 1],
                args.poses,
                args.solver_vels,
                args.local_mprops,
                args.colliders_len,
                args.sim_params,
                args.colliders_batch_capacity,
            )?;

            /*
             * Solve WITHOUT bias.
             */
            joint_solver.solve(pass, &mut joint_args, args.solver_vels, false)?;

            self.remove_cfm_and_bias_kernel.call(
                pass,
                args.contacts_len_indirect,
                args.constraints,
                args.contacts_len,
                args.contacts_batch_capacity,
            )?;

            self.reset_color.call(pass, 1u32, args.curr_color)?;
            for _ in 0..args.num_colors {
                self.step_gauss_seidel.call(
                    pass,
                    args.contacts_len_indirect,
                    args.constraints,
                    args.solver_vels,
                    args.constraints_colors,
                    args.contacts_len,
                    args.curr_color,
                    args.contacts_batch_capacity,
                    args.colliders_batch_capacity,
                )?;
                self.inc_color.call(pass, 1u32, args.curr_color)?
            }
        }

        /*
         * Writeback body velocities.
         */
        self.finalize.call(
            pass,
            [args.num_colliders, args.num_batches, 1],
            args.vels,
            args.solver_vels,
            args.colliders_len,
            args.colliders_batch_capacity,
        )?;

        Ok(())
    }
}
