#!/bin/bash
# Local (champagne) adaptation of build_unified_cubins.sh: cuda-oxide cubins
# for the migration stack (nexus-migrate + vortx-unified + khal-unified).
# Outputs to ~/rt_build/nexus_ptx. Consumed by khal-builder via
#   CUDA_OXIDE_SHADERS_PTX_NEXUS_RBD_SHADERS3D=$HOME/rt_build/nexus_ptx/nexus_rbd_shaders3d.cubin
#   CUDA_OXIDE_SHADERS_PTX_VORTX_SHADERS=$HOME/rt_build/nexus_ptx/vortx_shaders.cubin
set -eo pipefail
TOOL=$HOME/.rustup/toolchains/nightly-2026-04-03-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin
LIBDEV=$HOME/miniconda3/nvvm/libdevice/libdevice.10.bc
PTXAS=$HOME/miniconda3/bin/ptxas
BACKEND=$HOME/rt_build/cuda-oxide/crates/rustc-codegen-cuda/target/debug/librustc_codegen_cuda.so
export CUDA_OXIDE_PTX_DIR=$HOME/rt_build/nexus_ptx
mkdir -p "$CUDA_OXIDE_PTX_DIR"
export PATH=$HOME/.cargo/bin:$PATH

build_one () { # $1 workspace dir, $2 package, $3 features, $4 ll name, $5 crate src dir
  cd "$1"
  LL=$CUDA_OXIDE_PTX_DIR/$4.ll
  # `cargo clean -p` does not reliably invalidate cross-target build-std
  # artifacts (and cargo does not track the codegen-backend .so), so force
  # recompilation by touching the crate sources, then PROVE the .ll was
  # regenerated — a stale .ll silently benchmarks the previous backend.
  rm -f "$LL"
  find "$5" -name '*.rs' -exec touch {} +
  CARGO_INCREMENTAL=0 RUSTFLAGS="-Z codegen-backend=$BACKEND -Zalways-encode-mir -Zmir-enable-passes=-JumpThreading" \
    cargo +nightly-2026-04-03 build -p "$2" --release \
    --no-default-features --features "$3" \
    --target nvptx64-nvidia-cuda -Z build-std=core
  [ -s "$LL" ] || { echo "FATAL: $LL not regenerated by the shader build"; exit 1; }
  echo "ll: $(grep -c '^define' "$LL") defines"
  # Full post-link O3 REQUIRES function-level `convergent` attributes on the
  # defines (`) #0 {`): without them, loop unswitch/unroll clone bar.sync into
  # divergent branches -> sm_120 deadlock. The merged cuda-oxide main emits
  # them (upstream fix); refuse to O3 an .ll from an older backend.
  grep -q ') #0 {' "$LL" || { echo "FATAL: $LL lacks function-level convergent attrs — rebuild the cuda-oxide backend from main"; exit 1; }
  "$TOOL"/llvm-as "$LL" -o /tmp/u.bc
  "$TOOL"/llvm-link /tmp/u.bc "$LIBDEV" -o /tmp/u_linked.bc
  # Full O3 after linking libdevice. Measured on gpu_mb_gravity_and_lu
  # (unpacked tier) vs the bare internalize+globaldce lowering: 208 regs /
  # 1208B stack -> ~104 regs / 32B stack, all spills gone; G1@1024 +80%,
  # quad12@1024 +65% captured-replay throughput. -fp-contract=fast matches
  # the Vulkan driver's FMA contraction (neutral alone; the win is
  # inlining+SROA+loop opts).
  "$TOOL"/opt -passes="internalize,globaldce,default<O3>" /tmp/u_linked.bc -o /tmp/u_pruned.bc
  "$TOOL"/llc -mcpu=sm_120 -O3 -fp-contract=fast /tmp/u_pruned.bc -o /tmp/u.ptx
  "$PTXAS" -arch=sm_120 -O3 /tmp/u.ptx -o "$CUDA_OXIDE_PTX_DIR/$4.cubin"
  ls -la "$CUDA_OXIDE_PTX_DIR/$4.cubin"
}

build_one "$HOME/rt_build/nexus-migrate" nexus_rbd_shaders3d "cuda-oxide dim3 unsafe_remove_boundchecks" nexus_rbd_shaders3d "$HOME/rt_build/nexus-migrate/src_rbd_shaders"
build_one "$HOME/rt_build/vortx-unified" vortx-shaders "cuda-oxide" vortx_shaders "$HOME/rt_build/vortx-unified/vortx-shaders/src"
echo DONE
